import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ReactQueryProvider from "@/providers/react-query";

import { db } from "@/db";
import { Header } from "@/components/ui/common/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // 🔹 Busca categorias do banco
  const categories = await db.query.categoryTable.findMany({});

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 🔹 Header e app dentro do ReactQueryProvider */}
        <ReactQueryProvider>
          <Header categories={categories} />
          {children}
        </ReactQueryProvider>

        <Toaster position="top-center" />
      </body>
    </html>
  );
}
